# Generated by Django 4.1.7 on 2023-04-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Login', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='static\\img\\pg.png', upload_to='media/item_img/285593418'),
        ),
    ]
