# Generated by Django 4.1.7 on 2023-04-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Login', '0003_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='static\\img\\pg.png', upload_to='media/item_img/238699840'),
        ),
    ]
