# Generated by Django 4.1.7 on 2023-03-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Main', '0003_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='media/item_img')),
                ('image_2', models.ImageField(upload_to='media/item_img')),
                ('image_3', models.ImageField(upload_to='media/item_img')),
                ('image_4', models.ImageField(upload_to='media/item_img')),
                ('image_5', models.ImageField(upload_to='media/item_img')),
                ('name', models.CharField(max_length=264)),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('rented', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Web_Main.category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
