# Generated by Django 4.1.7 on 2023-03-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Main', '0004_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_1',
            field=models.ImageField(upload_to='media/item_img/507742795'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_2',
            field=models.ImageField(upload_to='media/item_img/329244838'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_3',
            field=models.ImageField(upload_to='media/item_img/832527056'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_4',
            field=models.ImageField(upload_to='media/item_img/177878098'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_5',
            field=models.ImageField(upload_to='media/item_img/854916218'),
        ),
    ]
