# Generated by Django 4.1.7 on 2023-03-23 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web_Main', '0007_alter_item_image_1_alter_item_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_1',
            field=models.ImageField(upload_to='media/item_img/443129812'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_2',
            field=models.ImageField(upload_to='media/item_img/443129812'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_3',
            field=models.ImageField(upload_to='media/item_img/443129812'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_4',
            field=models.ImageField(upload_to='media/item_img/443129812'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_5',
            field=models.ImageField(upload_to='media/item_img/443129812'),
        ),
    ]
