# Generated by Django 4.1.7 on 2023-04-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Main', '0009_alter_item_image_1_alter_item_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='district',
            field=models.CharField(choices=[('Atlantic Wharf', 'Atlantic Wharf'), ('Birchgrove', 'Birchgrove'), ('Butetown', 'Butetown'), ('Cardiff Bay', 'Cardiff Bay'), ('Cardiff city centre', 'Cardiff city centre'), ('Cardiff Gate', 'Cardiff Gate'), ('Castle Quarter', 'Castle Quarter'), ('Cathays Park', 'Cathays Park'), ('Cefn Mably', 'Cefn Mably'), ('Coryton, Cardiff', 'Coryton, Cardiff'), ('Culverhouse Cross', 'Culverhouse Cross'), ('Cyncoed', 'Cyncoed'), ('Danescourt', 'Danescourt'), ('Ely, Cardiff', 'Ely, Cardiff'), ('Gabalfa', 'Gabalfa'), ('The Hayes', 'The Hayes'), ('Cardiff International Sports Village', 'Cardiff International Sports Village'), ('Leckwith, Cardiff', 'Leckwith, Cardiff'), ('Llandaff', 'Llandaff'), ('Maindy', 'Maindy'), ('Mermaid Quay', 'Mermaid Quay'), ('Morganstown', 'Morganstown'), ('Mynachdy', 'Mynachdy'), ('Pentrebane', 'Pentrebane'), ('Plasdwr', 'Plasdwr'), ('Pwll-coch', 'Pwll-coch'), ('Radyr', 'Radyr'), ('Rhiwbina', 'Rhiwbina'), ('Rhydlafar', 'Rhydlafar'), ('Roath', 'Roath'), ('St Mellons', 'St Mellons'), ('Tiger Bay', 'Tiger Bay'), ('Tremorfa', 'Tremorfa')], default='Cardiff city centre', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_1',
            field=models.ImageField(upload_to='media/item_img/642361389'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_2',
            field=models.ImageField(upload_to='media/item_img/642361389'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_3',
            field=models.ImageField(upload_to='media/item_img/642361389'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_4',
            field=models.ImageField(upload_to='media/item_img/642361389'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_5',
            field=models.ImageField(upload_to='media/item_img/642361389'),
        ),
    ]
